name: CRM_BUILD
on: workflow_dispatch
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "Build CRM"
  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Test Step
        run: echo "Test CRM"
  Deploy:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Deploy Step
        run: echo "Deploy CRM"
